baseURL = 'https://example.org/'
title = "iLtc's Blog"
theme = 'PaperMod'
paginate = 7
enableEmoji = true
buildDrafts = false
buildFuture = false
buildExpired = false
defaultContentLanguageInSubdir = true

[services.disqus]
shortname = 'iltc-blog'

[markup]
[markup.goldmark]
duplicateResourceFiles = true

[params]
displayFullLangName = true
defaultTheme = "auto"
comments = true

[params.homeInfoParams]
Title = "iLtc's Blog"
Content = """
👋 Welcome to iLtc's Blog!
"""

[[params.socialIcons]]
name = "linkedin"
title = "Check out my LinkedIn"
url = "https://www.linkedin.com/in/alantluo/"

[[params.socialIcons]]
name = "github"
title = "Check out my GitHub"
url = "https://github.com/iLtc"

[[params.socialIcons]]
name = "gurushots"
title = "Check out my maps"
url = "https://maps.iltc.app/"

[[params.socialIcons]]
name = "goodreads"
title = "Check out my book list"
url = "https://lists.iltc.app/#/books"

[[params.socialIcons]]
name = "steam"
title = "Check out my video game list"
url = "https://lists.iltc.app/#/games"

[permalinks]
[permalinks.page]
posts = '/:slugorfilename'

[languages.en]
languageName = "English"
weight = 1

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[languages.zh]
languageName = "中文"
weight = 2
title = "iLtc 的博客"